#!/bin/bash 
#https://stackoverflow.com/questions/1729824/an-efficient-way-to-transpose-a-file-in-bash
cat $1 | sed 's/ /_/g' |
awk '               
{ 
for (i=1; i<=NF; i++)  {
	a[NR,i] = $i
	}
}
NF>p { p = NF }
END {    
for(j=1; j<=p; j++) {
	str=a[1,j]
	for(i=2; i<=NR; i++){
		str=str" "a[i,j];
		}
	print str
	}
}' | sed 's/ /	/g'  > $2
